wip

diff --git a/.github/workflows/ci-pr.yml b/.github/workflows/ci-pr.yml
--- a/.github/workflows/ci-pr.yml
+++ b/.github/workflows/ci-pr.yml
@@ -17,6 +17,7 @@ jobs:
     - uses: actions/checkout@v4
     - name: Install dependencies
       run: sudo apt-get update && sudo apt-get install -y $BASIC_PACKAGES
+    - run: exit 1 # Force fail
     - run: make
     - uses: actions/upload-artifact@v4
       with:
@@ -195,6 +196,7 @@ jobs:
     - uses: actions/checkout@v4
     - name: Install dependencies
       run: sudo apt-get update && sudo apt-get install -y $BASIC_PACKAGES
+    - run: exit 1 # Force fail
     - run: make bootstrap-full
 
   bench-fast:
